version: '3'
services:
  use-cases-module:
    build:
      context: .
      args:
        OS_UID: "${OS_UID}"
        OS_GID: "${OS_GID}"
    container_name: use-cases-module
    entrypoint: tail -f /dev/null
    volumes:
    - .:/module
